[project]
name = "examensarbete"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "huggingface-hub>=0.20.0",
    "numpy>=1.26.0",
    "onnx>=1.20.1",
    "optimum[onnxruntime]>=2.1.0",
    "torch>=2.10.0; sys_platform == 'linux'",
    "transformers>=4.36.0,<4.58.0",
]
